<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="python" Version="3.14.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevAppsExtension\DevAppsExtension.csproj" />
  </ItemGroup>

</Project>
